name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
        image: mcr.microsoft.com/playwright/python:v1.43.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        #   pip install -e .
      - name: Run your tests
        run: pytest
        # env:
        #   HOME: /root
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
            report_paths: report.xml